### ISSUE TITLE
weighted spectrum is unknown to the model

### ISSUE THREAD

**Issue by thierrynieus** [iomega/ms2query#182]
Dear authors,
I am working with an older version of ms2query (0.3.1 a branch, basically) which suits our needs. However, recently I started working with new data provided by Naicons  SRL, Milan and I am getting errors like:

"
    assert 100*missing_fractions[i] <= self.allowed_missing_percentage, \
AssertionError: 15.54 of weighted spectrum is unknown to the model."

in train_ms2deepscore()

In understand I can widen a bit the threshold of acceptance (maybe setting 20%) but I am unsure up to what level it is safe to change this parameter. In addition I am wondering if, instead, it wouldn't be better just ignore the items that do not fall into the range thus preventing the crash of the software.
Thanks for any feedback

**Comment by niekdejonge** [comment]
Dear Thierry,

It is fine to put this up to 100 percent. 
It is a setting to prevent running the model on spectra that have a lot of peaks that were not seen in the training data. So a spectrum that has many peaks that were not in the training data will give an AssertionError. It is good to have a warning about this because your results for this spectrum probably will not be reliable. However, the assertionError stops running completely which is not practical when running multiple spectra, since the rest will also not run.
Therefore I advise just setting it to 100 percent, since this will make sure this AssertionError is never raised.

Hope this helps!

**Comment by niekdejonge** [comment]
And I fully agree that for the purpose of MS2Query, it would be better to not raise the assertionError at all, however, this is not part of MS2Query but of one of our dependencies, so this was not easy to change. So setting it to 100 percent basically is a quick fix to prevent these AssertionErrors from happening.

**Comment by florian-huber** [comment]
We haven't systematically explored how drastic the consequences are of, say, 15 or 20% uncovered peak intensity. But of course, the higher this number gets, the less trustworthy will the score predictions be.

An alternative to work with this in a customized way would be to catch the exception using a try-except construction. But for large-scale computations that is not easily feasible, I guess.

In the future we might consider making this a bit more flexible. For instance by returning 0 scores when above the threshold.

**Comment by thierrynieus** [comment]
Thanks to all for your prompt and useful feedback!
