### ISSUE TITLE
Upgrade to new matchms release

### ISSUE THREAD

**Issue by niekdejonge** [iomega/ms2query#199]
Upgrade to new matchms release and replace ms2query steps that are now covered by matchms:
- Use the new pubchemlookup (this could also be achieved without upgrading matchms
- Replace the cleaning steps with Pipeline

**Comment by mapio** [comment]
Fixing this would be great since now I've a `WARNING:matchms:interpret_pepmass:Overwriting existing precursor_mz` message for every spectrum, from `matchms/filtering/metadata_processing/interpret_pepmass.py` probably due to the fact that ,in the used version of `matchms`, such warning is not guarded by the `and _substantial_difference` part of the if clause at line 42 in the current version.
