### ISSUE TITLE
"Harmonizing annotations" degrades in peformance over time.

### ISSUE THREAD

**Issue by mapio** [iomega/ms2query#227]
Now that the example with 1.5k spectra runs, we attempted to scale to 490k spectra from GNPS.

Unfortunately, after few hours of computation the logs are filling with errors related to the "Harmonizing annotations" step and the speed reported by the progress meter dropped to 1it/s (on the small dataset was around 90it/s).

Code inspection reveals that the issue could be the fact that the step involves Pubchem querying and, as in the case of the classifire, this introduces a dependency on an external API that (especially under such an heavy load) can malfunction, or throttle the requests.

So I'm again asking you: is this step avoidable? I've seen that (as in the case of the classifire) there is a bool parameter that could be set to False. Is again the case that the library will be correctly created without Pubchem access?

In case, do you want me to make a PR, or would you like to do it yourself?

**Comment by niekdejonge** [comment]
Good to hear the 1.5k spectra do run. 

The pubchem lookup can be disabled safely. The reason we added it is that many of the public libraries have annotations in the form of a compound name, but no structure like smiles, inchi, inchikey. Pubchem lookup checks pubchem for the compound name and if the parent mass and compound name match the smiles will be taken from there. 

I did run into this issue of instability of pubchem lookup myself as well and therefore implemented a more stable version in matchms directly. However, since newer matchms versions use pandas 2.0 and some other things that are not fully backwards compatible, it was not straightforward to go to this newer version. I hope to do this soon, so the fixes we implemented in matchms also benefit MS2Query. 

In the meantime, you can disable the pubchem lookup within MS2Query. Alternatively, you could also do preprossing of the spectra by first using the new version of matchms and inputting these spectra into ms2query after the processing of matchms.

**Comment by mapio** [comment]
Thank you for your explanation. I'm about to make a PR with the code changes required to be able to disable the Pubchem lookup calling `clean_and_train_models`.
