### ISSUE TITLE
“feature_id” column empty

### ISSUE THREAD

**Issue by montmasis** [iomega/ms2query#234]
Hello

the MS2Query job was completed successfully – however, the “feature_id” column in the report is empty.  
Do you know why that could be the reason?
In my mgf spectra (MS-DIAL output) the feature ID is named "SCANS=" as it is in your dummy example mgf file.

Thanks

Stefano

**Comment by niekdejonge** [comment]
Hi Stefano,

You can add the columns that you want to add from your metadata by adding:
--additional_metadata 
The default is to add feature_id and retention_time, but in your case this should be changed to:
--additional_metadata retention_time scans
This should add a column with the values stored under scans. 

Hope that helps!

**Comment by montmasis** [comment]
Great, thanks!

Stefno

**Comment by niekdejonge** [comment]
@montmasis I just noticed your reply here, missed it before. 

Thanks for your suggestion!

We indeed skip spectra with less than 3 fragments, since annotations will be unreliable. We do however add a column with "query_spectrum_nr" which has the number of the spectrum in the order as they appeared in the spectrum file (even if no query_spectrum_nr is specified in that file). In this way you can always cross reference your results with the spectra in your file. or even better by using the --additional_metadata you can add feature_ids (or other column) to clearly link the spectra and the results. 

Your suggestion would have been a good solution as well! One downside is that some files of users contain many MS1 spectra (which are also filtered out), this would result in 100s of empty lines in the results of MS2Query, which is also not very user friendly, for these cases.

I am not yet sure which solution is most user friendly for the average user, but I understand your issue. We will later this year probably do a complete refactoring of MS2Query, at that point I will reconsider your suggestion, since with the current code structure it is not super trivial to make that change.

**Comment by montmasis** [comment]
Thanks for considering!
