### ISSUE TITLE
Store reference structural similarity scores (Tanimoto)

### ISSUE THREAD

**Issue by florian-huber** [iomega/ms2query#55]
Since the library data is static and will not change (unless with library version updates), we can save a lot of computation by using pre-calculated Tanimoto score between all possible InChIKey combinations.

So far, this is done by reading only a fraction of the data from a numpy array (see `get_library_similarities()` function from https://github.com/iomega/ms2query/blob/main/ms2query/app_helpers.py).

We could:
- (1) adapt the mentioned solution
- (2) find an alternative tabular solution that quickly gives access to score[i, j]
- (3) build a SQLite type solution by storing the top-x compounds for each InChIKey, say a list like `[(spectrum_id1, score), ...]`

**Comment by niekdejonge** [comment]
After searching for different options these are the options I could find:
1: Adapt the mentioned solution:
There is an option to not load a full csv file, but instead line by line into memory as described on https://stackoverflow.com/questions/29334463/how-can-i-partially-read-a-huge-csv-file 
This could be an option, if we for instance store the line number of each inchikey in a dictionary, so only the line has to be loaded that contains the scores that we need.
2: For other alternatives more database like structures were mentioned like HDF5, but might be better to stick to SQLite in this case, to keep it uniform (or switch everything to HDF5). An alternative might be numpy.memmap, this functions similar to the above mentioned method with csv files. Found at: https://stackoverflow.com/questions/30329726/fastest-save-and-load-options-for-a-numpy-array
3: Benefit is, I am already familiar with SQLite and will work without loading everything in memory. The table with tanimoto scores can be loaded into the same sqlite file as the file with the metadata (in same table, or different table linked by foreign key). Since indexing* is used, I expect that looking up values in sqlite will be quicker or as quick as loading from a csv file via the above mentioned method. Looking up specific tanimoto scores (between two inchikeys) is possible, when stored in a table. 

*Indexing is basically creating a dictionary that stores the row at which a value is stored. SQLite does this automatically for your primary key. https://www.sqlitetutorial.net/sqlite-index/

**Comment by niekdejonge** [comment]
Decided for going for implementation in SQLite. 

Initial plan was storing the tanimoto score in a big matrix with dimension 120000:12000 like:
           Inchi1 Inchi2 Inci3 etc.
Inchi1    1.0      0.3     0.2
inchi2    0.3      1.0     0.4
inchi3   0.2       0.4     1.0
etc.

However, this is not possible due to a limitation in the number of columns in sqlite (2000). The default maximum number of columns can be changed, but is not adviced, since sqlite uses algorithms that are O(N^2) and would therefore be probably very slow. https://www.sqlite.org/limits.html

As an alternative the table is converted by a melt function. 
To give a table structure with dimension [3:144000] like:

Inchi1 Inchi1 1.0
Inchi1 Inchi2 0.3
Inchi1 Inchi3 0.2
etc.
Inchi2 Inchi1 0.3
Inchi2 Inchi2 1.0
inchi2 inchi3 0.4
etc. 

This is the correct way of storing a matrix in a database. 

We should still decide if we want to remove duplicates from the data and how this can be done efficiently.
This means the top 20 will not be stored in this table, but in a separate table instead, which is fine.

**Comment by niekdejonge** [comment]
New choices made:

**Store inchikeys as numbers**
Storing text is less memory efficient than storing numbers. Loading tanimoto scores from the previous database structure, took more than a second (for one score). Instead the inchikeys will be stored in a seperate table with their corresponding numbers. That than can be used to look up the corresponding tanimoto scores. 

**Removing duplicates**
In the .npy file duplicates were stored, meaning that both inchi1 inchi2 and inchi2, inchi1 was stored, which is both the same number. This results in double the size, and a slower loading time. 

**Add a primary key before creating the table**
A primary key speeds up the lookup time, by indexing the columns. The columns inchikey1 and inchikey2 are together the composite key (primary key consisting of two columns). Adding the primary key after creating the table, is advised for most databases, since this is often quicker, however this is not possible for sqlite, so the primary keys are assigned before loading the data into the table.

**Comment by niekdejonge** [comment]
This is implemented with #56, integrating with rest of functions is discussed in #46.
