### ISSUE TITLE
re-evaluate storing Tanimoto scores

### ISSUE THREAD

**Issue by florian-huber** [iomega/ms2query#76]
The entire Tanimoto scores database (`sqlite`) is something we might want to reconsider.
The reason I bring this up is (1) it is getting quiet big (>2GB for the current 17k Inchikeys) and might not be accessed that often (not sure!).

We could compare it with a solution that stores 17k molecular fingerprints to calculate those scores from once needed.
Or even with a solution that computes everything from scratch when needed (--> fingerprints --> scores).

**Comment by justinjjvanderhooft** [comment]
That is quite sizeable indeed.... There may be fast ways to compute structural similarities on the fly indeed....

**Comment by niekdejonge** [comment]
I think one solution that already would work now is removing the tanimoto scores from sqlite and only storing the top best matching tanimoto scores for each inchikey. (already implemented) This is the information needed to calculate a average ms2ds score for closely related inchikeys. 
However if we want to later add networking again between the top results, we would need to calculate the tanimoto scores between the top matches. Depending on how much time calculating tanimoto scores from scratch is, between for instance 20*20 inchikeys, we could decide to do this from scratch or using prestored fingerprints.

**Comment by niekdejonge** [comment]
In addition to not storing the tanimoto scores, we might actually also remove all peaks/intensities stored, since they are not needed for calculating MS2Deepscore and Spec2Vec scores (the embeddings are used). The peaks were originally stored for being able to calculate cosine/modified cosine scores, but cosine scores will probably not be used anymore, since they do not add a lot of accuracy, while taking very long to calculate. 

I still think it is good to leave the current structure in place, until we settle on the final structure of MS2Query, so we are sure that peaks or tanimoto scores are not needed for future additions to MS2Query. (e.g. networking based on tanimoto scores or adding scores that need peaks/intensities)

**Comment by justinjjvanderhooft** [comment]
The peak (and loss) intensities would be useful for visualization options and in that sense could be useful to store/have. I think this is something to keep in mind.
